services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8084:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/index.html:/usr/share/nginx/html/index.html:ro
    depends_on:
      - tracker
    restart: unless-stopped

  tracker:
    build: ./tracker
    container_name: tracker
    volumes:
      - ./tracker/data:/app/data
    environment:
      - TZ=Asia/Yekaterinburg
    restart: unless-stopped

  mailer:
    build: ./mailer
    container_name: mailer
    network_mode: host
    volumes:
      - ./mailer/data:/app/data
      - ./mailer:/app
    restart: unless-stopped

volumes:
  tracker_data:
