events {}
http {
    # Ссылка на python контейнер tracker
    upstream tracker_api {
        server tracker:8000;
    }
    server {
        # Слушаем внутренний порт 80
        listen 80;
        charset utf-8; # Поддержка кириллицы
        
        location / {
            # Создаем копию запроса в фоновом режиме для трекинга
            mirror /mirror_track; 

            root /usr/share/nginx/html;
            index index.html;
        }

        # Блок для трекера
        location /mirror_track {
            internal; # Блок прямого доступа к URL снаружи

            # Отправка запроса со всеми параметрами в Python API
            proxy_pass http://tracker_api/track$is_args$args;
            proxy_set_header X-Forwarded-For $remote_addr;
        }
    }
}