events {}
http {
    server {
        # Слушаем внутренний порт 80
        listen 80;
        charset utf-8; # Поддержка кириллицы
        
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }
}